### PR TITLE
feat: Linux support

### PR DESCRIPTION
**Pull request by tupoy-ya**
feat(Crossmap): Updated crossmap from YimMenu.
feat(Natives): Updated natives from https://github.com/alloc8or/gta5-nativedb-data.
feat(CI): Make CI run on push.
feat(Functions DB): Added some maintransition functions.

TODO:
- [x] Fix windows build not showing GUI.
- [x] Add cli arguments.
- [x] Test for collisions in new functions.

I have zero experience with .net, C#, wpf, so there may be stupid mistakes.

### CODE REVIEW

**Review by maybegreat48 — CHANGES_REQUESTED** [review]
Where can I find the source for these DLL files that you've added? Can't you just add a nuget module and build it when building the project?

**Comment by tupoy-ya** [comment]
> Where can I find the source for these DLL files that you've added? Can't you just add a nuget module and build it when building the project?

Source:
https://www.nuget.org/packages/CommandLineParser
https://github.com/commandlineparser/commandline

I added them by running `nuget install CommandLineParser` in `GTA-V-Script-Decompiler/packages/` directory, which looks similar to how [FCTB.2.16.11.0](https://github.com/maybegreat48/GTA-V-Script-Decompiler/tree/master/packages/FCTB.2.16.11.0) is installed, i don't know how to make it so they are built from source.

**Comment by maybegreat48** [comment]
Yeah, that makes sense

**Comment by maybegreat48** [comment]
Feel free to open an issue if I accidentally break the Linux build

**Pull request merged**
